{"uuid": "fe366c96-689f-4ed4-8278-73f171698b2f", "children": ["4cbda4db-6931-4d71-9c6e-4f372640c540", "c2b89433-f523-47e3-8043-5db0ee23f91d"], "befores": [{"name": "test_failed_check", "status": "passed", "start": 1594283081231, "stop": 1594283081231}], "afters": [{"name": "test_failed_check::0", "status": "broken", "statusDetails": {"message": "ValueError: stat: embedded null character in path\n", "trace": "  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\yosefev\\IdeaProjects\\TheBasics\\Sellenium\\browserTest.py\", line 72, in test_failed_check\n    take_screenshot(driver, request.node.name)\n  File \"C:\\Users\\yosefev\\IdeaProjects\\TheBasics\\Sellenium\\browserTest.py\", line 85, in take_screenshot\n    allure.attach.file(driver.get_screenshot_as_png(),\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 167, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_pytest\\listener.py\", line 219, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\reporter.py\", line 113, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\logger.py\", line 53, in report_attached_file\n    shutil.copy2(source, destination)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shutil.py\", line 432, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shutil.py\", line 240, in copyfile\n    if _samefile(src, dst):\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shutil.py\", line 217, in _samefile\n    return os.path.samefile(src, dst)\n  File \"C:\\Users\\yosefev\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\genericpath.py\", line 100, in samefile\n    s1 = os.stat(f1)\n"}, "attachments": [{"name": "test_open_search_not_found", "source": "3188c32f-3a6e-4d2c-ae4a-a51d2e96019f-attachment.png", "type": "image/png"}], "start": 1594283084867, "stop": 1594283086507}], "start": 1594283081231, "stop": 1594283086507}